#!/usr/bin/env zsh
#  write tests
#  run tests using buttercup-run-discover
LE_EMACS=${EMACS:-emacs}

emacs_args=(
    -Q -batch -nw
    -L ./
    -l frecentf-tests
    -f buttercup-run-discover
)

exec $LE_EMACS $emacs_args
